import {
  AlignJustify,
  AlignLeft,
  ArrowUpDown,
  ChevronRight,
  CircleX,
  Facebook,
  File,
  GraduationCap,
  Instagram,
  LayoutGrid,
  Loader2,
  LogOut,
  LucideIcon,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings2,
  SquareArrowOutUpRight,
  Trash,
  UserRound,
  Youtube,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  graduationCap: GraduationCap,
  alignLeft: AlignLeft,
  spinner: Loader2,
  file: File,
  search: Search,
  user: UserRound,
  layoutGrid: LayoutGrid,
  logOut: LogOut,
  alignJustify: AlignJustify,
  arrowUpDown: ArrowUpDown,
  plus: Plus,
  chevronRight: ChevronRight,
  phone: Phone,
  yt: Youtube,
  facebook: Facebook,
  instagram: Instagram,
  openLink: SquareArrowOutUpRight,
  pencil: Pencil,
  trash: Trash,
  settings: Settings2,
  error: CircleX,
};
