import {
  LucideIcon,
  GraduationCap,
  AlignLeft,
  BookOpenText,
  BriefcaseBusiness,
  Notebook,
  BarChart3,
  FileWarning,
  Loader2,
  File,
  Search,
  UserRound,
  LayoutGrid,
  LogOut,
  AlignJustify,
  ArrowUpDown,
  Plus,
  ChevronLeft,
  ChevronRight,
  Phone,
  Youtube,
  Facebook,
  Instagram,
  SquareArrowOutUpRight,
  Pencil,
  Trash,
  Settings2,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  graduationCap: GraduationCap,
  alignLeft: AlignLeft,
  openBook: BookOpenText,
  suitCase: BriefcaseBusiness,
  notebook: Notebook,
  chart: BarChart3,
  warning: FileWarning,
  spinner: Loader2,
  file: File,
  search: Search,
  user: UserRound,
  layoutGrid: LayoutGrid,
  logOut: LogOut,
  alignJustify: AlignJustify,
  arrowUpDown: ArrowUpDown,
  plus: Plus,
  back: ChevronLeft,
  chevronRight: ChevronRight,
  phone: Phone,
  yt: Youtube,
  facebook: Facebook,
  instagram: Instagram,
  openLink: SquareArrowOutUpRight,
  pencil: Pencil,
  trash: Trash,
  settings: Settings2
};
